#!/bin/bash


## This Bash script performs a series of tasks related to a Maven 
 ## project using the Maven command-line tool. Here's a breakdown of each 
 ## command:
 ## 
 ## 1. `mvn`: This is the command used to run Maven commands from the 
 ## command line.
 ## 2. `clean`: This is a Maven goal that removes all files generated by 
 ## the previous build.
 ## 3. `compile`: This Maven goal compiles the source code of the project.
 ## 4. `spring-boot:process-aot`: This is a specific Maven goal related 
 ## to Spring Boot's Ahead-Of-Time compilation feature, which processes 
 ## classes for AOT compilation.
 ## 5. `package`: This Maven goal packages the compiled code into a 
 ## distributable format, such as a JAR file.
 ## 
 ## In summary, this script cleans the project, compiles the source code, 
 ## processes classes for AOT compilation in the context of Spring Boot, 
 ## and packages the compiled code into a distributable format.


  mvn clean compile spring-boot:process-aot package
  
