
version: '3.1'

services:

  akhq:
    image: tchiotludo/akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: host.docker.internal:9092

    ports:
      - "8182:8080"
    


